---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb
  labels:
    app.kubernetes.io/component: mongodb
type: Opaque
data:
  mongodb-root-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- if .Values.mongodb.password }}
  mongodb-password:  {{ .Values.mongodb.password | b64enc | quote }}
  {{- else }}
  mongodb-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sigo-mongo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sigo-mongo
spec:
  selector:
    matchLabels:
      app: sigo-mongo
  template:
    metadata:
      labels:
        app: sigo-mongo
    spec:
      containers:
        - name: sigo-mongo
          image: mongo
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: storage
              mountPath: /data/db
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: sigo-mongo
---
apiVersion: v1
kind: Service
metadata:
  name: sigo-mongo
spec:
  selector:
    app: sigo-mongo
  ports:
    - port: 27017
      targetPort: 27017
---

